### ISSUE TITLE
Unable to get example plugin code from documentation working

### ISSUE THREAD

**Issue by endemics** [hashicorp/sentinel-sdk#12]
Hi,

I'm trying to build the example code from https://docs.hashicorp.com/sentinel/extending/dev but am unable to get it to work so far.

The produced binary seems to be compiled to support netrpc only and not grpc:
```
2018-09-03T12:16:02.418Z [DEBUG] plugin: starting plugin: path=/usr/local/bin/sentinel-test args=[/usr/local/bin/sentinel-test]
2018-09-03T12:16:02.429Z [DEBUG] plugin: waiting for RPC address: path=/usr/local/bin/sentinel-test
2018-09-03T12:16:02.458Z [DEBUG] plugin.sentinel-test: plugin address: timestamp=2018-09-03T12:16:02.458Z address=/tmp/plugin485228174 network=unix
2018-09-03T12:16:02.461Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/sentinel-test
Runtime error while running the policy:

sentinel.policy:1:1: Unsupported plugin protocol "netrpc". Supported: [grpc]

A runtime error is a non-recoverable error and always represents a bug
in the policy. When a runtime error is experienced, the result of the
policy is "false". Please fix the error above and try again.

Execution trace. The information below will show the values of all
the rules evaluated and their intermediate boolean expressions. Note that
some boolean expressions may be missing if short-circuit logic was taken.


make: *** [all] Error 3
```

I am not sure why this is the case as I believe the sentinel-sdk should make the go-plugin library switch to using grpc since it has the line `GRPCServer: goplugin.DefaultGRPCServer,` @ https://github.com/hashicorp/sentinel-sdk/blob/master/rpc/serve.go#L46

I have created a [repository with the code that I am trying to build](https://github.com/endemics/sentinel-test), containing the instructions needed in the Readme file to reproduce the issue (I have vendored the dependencies and locked the sentinel binary version as well so it should be 100% reproduceable).

**Comment by aidanSoles** [comment]
It would be helpful to have an example to go off of as a starting point. As for the error @endemics is having, I was able to replicate it too using his repo [here](https://github.com/endemics/sentinel-test).

**Comment by vancluever** [comment]
The root cause of this was due to the SDK tracking an older version of [go-plugin](https://github.com/hashicorp/go-plugin).

We are tracking master again, but we will be converting this to use modules soon here so that there's no ambiguity surrounding current dependencies.

Related: #15
