### ISSUE TITLE
sdk needs to be vendored

### ISSUE THREAD

**Issue by scottwinkler** [hashicorp/sentinel-sdk#15]
Yesterday I was able to create an import plugin following the example in the documentation with no issues. Today the same code does not work, I get the following error (which I do not get with the binary from yesterday)

```
test.sentinel:1:1: Error configuring import "time": rpc error: code = Unknown desc = invalid import implementation, please report a bug to the developer of this import
```
Furthermore, I have not been able to build any imports, not even a trivial example shown here: https://github.com/scottwinkler/sentinel-example-import. I get the same error: 

```
example.sentinel:1:1: Error configuring import "example": rpc error: code = Unknown desc = invalid import implementation, please report a bug to the developer of this import
```

I suspect an issue with the rpc library that the sentinel sdk is using, since there have been no recent commits to the sdk. By vendoring the sdk with either dep or govendor, this problem should be fixed.

**Comment by vancluever** [comment]
This is now resolved via an updated version of go-plugin and the conversion to modules.
