### ISSUE TITLE
No uniformity of functionality because module() call doesn't work locally

### ISSUE THREAD

**Issue by aidanSoles** [hashicorp/sentinel-sdk#16]
Per the docs [here](https://www.terraform.io/docs/enterprise/sentinel/import/mock-tfstate.html):

```
There are currently some limitations mocking tfstate data in Sentinel. These issues
will be fixed in future releases of the import and core runtime.

As functions cannot be mocked in the current Sentinel testing framework, the
module() function is not available. As a result, only root module data can be mocked
at this time.
```

This is a huge limitation when using `sentinel test` because the call to `module()` only works when policies are run in TFE. `module()` calls don't work locally, even if the local testing data is formatted to match the structure of the `tfplan` data in TFE.

So, as it stands, a policy can't be reliably written using the Sentinel simulator and local test data, then picked up and dropped in to TFE as is because the call to `module()` doesn't exist in both environments--which is the ideal workflow.

**Comment by sarcasticadmin** [comment]
This issue is also mentioned here: https://github.com/hashicorp/terraform-guides/issues/64

**Comment by aidanSoles** [comment]
The 0.8.0 release allows the `module(...)` [functionality to be mocked](https://docs.hashicorp.com/sentinel/commands/config#mocking-with-sentinel-code), so it can now be worked around (whereas there was no straightforward workaround before). The ideal workflow (IMO) would be to mimic the [data format that exists in TFE](https://www.terraform.io/docs/enterprise/sentinel/import/tfplan.html#the-namespace) and have the `module(...)` call act as it does in TFE, instead of having to mock the `module(...)` function _and_ the data.
